# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ebaa2a26018f7ab688900859c9e2dc0a4fa2603e106ffb27a6a093e4c0f288099aac2f89fe24e9f777dd6c7df041e826c854f674a1390f4cacd3e785eda931

test:
  secret_key_base: c6c5daa1f9c64dfdf070ee85ba448dd6a839f2b0bbd9684bf85345b7af0532ea548d0b41a9d8c51edbb52e3085dea3632dfd4a69897ec86fd0b011977a41ed6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
